function RandomForest()
clc
close all
clear all

X=importfile('MatlabData.mat')

XP=dataPAll(:,1:3);


% Mdl = TreeBagger(100,Displacement,MPG,'Method','regression');


end
% https://www.mathworks.com/help/stats/treebagger.html

function importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 04-Apr-2017 22:32:52

% Import the file
newData1 = load('-mat', fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
end